#version 3.5;

#include "colors.inc"  
#include "finish.inc"  

global_settings{SAR_Output_Data 1 SAR_Intersection 0} // activate line only for adapted POV-Ray!

// SAR_Output_Data --> write signal information to file [yes/no]
// SAR_Intersection --> write intersection points to file [yes/no]

// POV-File generated by Stefan Auer
// German Aerospace Center, DLR, 2015

// see file "Step_Simulation_Documentation.pdf" for simulation instructions

// rendering: 1000 x 1200 pixels

// Sensor
#declare Cam = camera {
  orthographic
  location <0,60,-60>    // location of virtual SAR, far field -> orthographic projection
  look_at  <0,0,0>
  right 100*x            // horizontal size of view
  up 120*y               // vertical size of view
}

// Insert Cam
camera{Cam} 

// Light source
light_source {
  <0, 60, -60>
  color rgb <1,1,1>       // light's color
  parallel
  point_at <0, 0, 0>      // direction of spotlight
}   

// Ground plane
plane {
  <0,1,0> // <X Y Z> unit surface normal, vector points "away from surface"
   0 // distance from the origin in the direction of the surface normal
  //hollow on // has an inside pigment?       
  pigment {color White}
  finish {reflection {0.5} ambient 0 diffuse 0.1 specular 0} 
}  

// Define step model
#declare step_model = union{
   
        // Step model components
        box{  
            // create a box that extends between the 2 specified points
            <-10, 20, -10>  // one corner position <X1 Y1 Z1>
            <10, 0, 10>  // other corner position <X2 Y2 Z2>  
        }  

        box{  
            // create a box that extends between the 2 specified points
            <-10, 40, -10>  // one corner position <X1 Y1 Z1>
            <10, 0, 10>  // other corner position <X2 Y2 Z2> 
            translate <0,0,20>       
        }    
}     

// Insert step model to scene
object {step_model
        translate <0,0,0> // adapt if necessary
        rotate <0,0,0>  // adapt second value for rotation (y -> height axis)
        pigment {color White} 
        finish {reflection {0.5} ambient 0 diffuse 0.3 specular 0.7 roughness 0.005}
}




 



     







   



